version: '3.9'
services:
  development:
    container_name: myapp
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - /workspaces/myapp/node_modules
